FROM samurais/tensorflow-serving:v1.0.0                                                                                                                             [22/72]
MAINTAINER Hain Wang <hailiang.hl.wang@gmail.com>
